import { VERSION } from "./constants.mjs";
import {
  localize,
  styleCommand,
  styleHeading,
  styleMuted,
} from "./lib/ui.mjs";

export function helpText() {
  const lines = [
    styleHeading(`nimicoding ${VERSION}`),
    "",
    localize("Usage:", "用法："),
    `  ${styleCommand("nimicoding --help")}`,
    `  ${styleCommand("nimicoding --version")}`,
    `  ${styleCommand("nimicoding start")}`,
    `  ${styleCommand("nimicoding start --yes")}`,
    `  ${styleCommand("nimicoding start --host <generic|codex|claude|oh-my-codex>")}`,
    `  ${styleCommand("nimicoding clear")}`,
    `  ${styleCommand("nimicoding clear --yes")}`,
    `  ${styleCommand("nimicoding sync [--apply|--check|--dry-run] [--json]")}`,
    `  ${styleCommand("nimicoding topic create <slug> --justification <text> [--title <text>] [--json]")}`,
    `  ${styleCommand("nimicoding topic status [<topic-id>|<topic-path>] [--json]")}`,
    `  ${styleCommand("nimicoding topic run-next-step <topic-id> [--json]")}`,
    `  ${styleCommand("nimicoding topic run-ledger <init|record|build|status> <topic-id> --run-id <id> [--json]")}`,
    `  ${styleCommand("nimicoding topic-runner <step|run> <topic-id> --run-id <id> --adapter <codex|oh_my_codex|claude> [--execute-host] [--json]")}`,
    `  ${styleCommand("nimicoding topic validate [<topic-id>|<topic-path>] [--json]")}`,
    `  ${styleCommand("nimicoding topic validate graph <topic-id> [--json]")}`,
    `  ${styleCommand("nimicoding topic validate admission <topic-id> <wave-id> [--json]")}`,
    `  ${styleCommand("nimicoding topic wave add <topic-id> <wave-id> <slug> --goal <text> --owner-domain <text> [--dep <wave-id>] [--json]")}`,
    `  ${styleCommand("nimicoding topic wave select <topic-id> <wave-id> [--json]")}`,
    `  ${styleCommand("nimicoding topic wave admit <topic-id> <wave-id> [--json]")}`,
    `  ${styleCommand("nimicoding topic packet freeze <topic-id> --from <draft-path> [--json]")}`,
    `  ${styleCommand("nimicoding topic worker dispatch <topic-id> --packet <packet-id> [--json]")}`,
    `  ${styleCommand("nimicoding topic audit dispatch <topic-id> --packet <packet-id> [--json]")}`,
    `  ${styleCommand("nimicoding topic result record <topic-id> --kind <worker|implementation|audit|preflight|judgement> --verdict <PASS|NEEDS_REVISION|FAIL|OVERFLOW> --from <path> --verified-at <iso8601> [--json]")}`,
    `  ${styleCommand("nimicoding topic remediation open <topic-id> --kind <a|b|continuation|execution-state-closure> --reason <token> [--overflowed-packet <packet-id>] [--json]")}`,
    `  ${styleCommand("nimicoding topic overflow continue <topic-id> --packet <continuation-packet-id> --overflowed-packet <packet-id> --manager-judgement <text> --same-owner-domain [--json]")}`,
    `  ${styleCommand("nimicoding topic hold <topic-id> --reason <token> --summary <text> [--reopen-criteria <text>] [--close-trigger <text>] [--json]")}`,
    `  ${styleCommand("nimicoding topic resume <topic-id> --criteria-met <text> [--json]")}`,
    `  ${styleCommand("nimicoding topic validate closure <topic-id> <wave-id> [--json]")}`,
    `  ${styleCommand("nimicoding topic closeout wave <topic-id> <wave-id> --authority <open|closed|blocked> --semantic <open|closed|blocked> --consumer <open|closed|blocked> --drift-resistance <open|closed|blocked> --disposition <complete|partial|deferred> [--json]")}`,
    `  ${styleCommand("nimicoding topic true-close-audit <topic-id> --judgement <text> [--json]")}`,
    `  ${styleCommand("nimicoding topic closeout topic <topic-id> --authority <open|closed|blocked> --semantic <open|closed|blocked> --consumer <open|closed|blocked> --drift-resistance <open|closed|blocked> --disposition <complete|partial|deferred> [--json]")}`,
    `  ${styleCommand("nimicoding topic decision-review <topic-id> <slug> --decision <text> --replaced-scope <text> --active-replacement-scope <text> [--disposition <retired|superseded|unchanged>] [--target-wave <wave-id>] [--date <YYYY-MM-DD>] [--json]")}`,
    `  ${styleCommand("nimicoding doctor")}`,
    `  ${styleCommand("nimicoding doctor --verbose")}`,
    `  ${styleCommand("nimicoding doctor --json")}`,
    `  ${styleCommand("nimicoding blueprint-audit [--blueprint-root <path>] [--canonical-root <path>] [--json] [--write-local]")}`,
    `  ${styleCommand("nimicoding handoff --skill <skill-id>")}`,
    `  ${styleCommand("nimicoding handoff --skill <skill-id> --json")}`,
    `  ${styleCommand("nimicoding handoff --skill <skill-id> --prompt")}`,
    `  ${styleCommand("nimicoding sweep audit plan --root <dir> [--criteria <csv>] [--exclude <csv>] [--max-files <n>] [--sweep-id <id>] [--json]")}`,
    `  ${styleCommand("nimicoding sweep audit chunk dispatch --sweep-id <id> --chunk-id <chunk-id> --dispatched-at <iso8601> [--auditor <id>] [--json]")}`,
    `  ${styleCommand("nimicoding sweep audit chunk audit-codex --sweep-id <id> --chunk-id <chunk-id> --dispatched-at <iso8601> --verified-at <iso8601> --reviewed-at <iso8601> [--from-raw-output <ref>] [--timeout-ms <ms>] [--json]")}`,
    `  ${styleCommand("nimicoding sweep audit chunk audit-claude --sweep-id <id> --chunk-id <chunk-id> --dispatched-at <iso8601> --verified-at <iso8601> --reviewed-at <iso8601> [--from-raw-output <ref>] [--timeout-ms <ms>] [--json]")}`,
    `  ${styleCommand("nimicoding sweep audit chunk ingest --sweep-id <id> --chunk-id <chunk-id> --from <json> --verified-at <iso8601> [--json]")}`,
    `  ${styleCommand("nimicoding sweep audit chunk review --sweep-id <id> --chunk-id <chunk-id> --verdict <pass|fail> --reviewed-at <iso8601> [--summary <text>] [--json]")}`,
    `  ${styleCommand("nimicoding sweep audit chunk skip --sweep-id <id> --chunk-id <chunk-id> --reason <text> --skipped-at <iso8601> [--json]")}`,
    `  ${styleCommand("nimicoding sweep audit ledger build --sweep-id <id> [--verified-at <iso8601>] [--json]")}`,
    `  ${styleCommand("nimicoding sweep audit remediation-map build --sweep-id <id> [--max-findings <n>] [--verified-at <iso8601>] [--json]")}`,
    `  ${styleCommand("nimicoding sweep audit finding resolve --sweep-id <id> --finding-id <id> --disposition <remediated|accepted-risk|false-positive|deferred-backlog> --from <json> --verified-at <iso8601> [--json]")}`,
    `  ${styleCommand("nimicoding sweep audit closeout summary --sweep-id <id> --verified-at <iso8601> [--json]")}`,
    `  ${styleCommand("nimicoding sweep audit status --sweep-id <id> [--json]")}`,
    `  ${styleCommand("nimicoding sweep design intake --sweep-id <id> [--run-id <id>] [--json]")}`,
    `  ${styleCommand("nimicoding sweep design packet-build --run-id <id> --packet-id <id> (--finding-id <id>|--finding-ids <csv>) [--explicit-question <text>] [--prior-design-state-refs <csv>] [--prior-design-state-marker <state>] [--current-cluster-refs <csv>] [--current-wave-refs <csv>] [--authority-only] [--json]")}`,
    `  ${styleCommand("nimicoding sweep design packet-build-batch --run-id <id> --batch-size <n> [--finding-ids <csv>] [--packet-prefix <id>] [--manifest-id <id>] [--explicit-question <text>] [--json]")}`,
    `  ${styleCommand("nimicoding sweep design auditor-prompt --run-id <id> --packet-id <id> [--json]")}`,
    `  ${styleCommand("nimicoding sweep design result-ingest --run-id <id> --from <yaml> [--mode <focused|all>] [--json]")}`,
    `  ${styleCommand("nimicoding sweep design ledger-validate --run-id <id> [--json]")}`,
    `  ${styleCommand("nimicoding sweep design finalize --run-id <id> [--json]")}`,
    `  ${styleCommand("nimicoding sweep design wave-plan --run-id <id> --topic-id <id> [--json]")}`,
    `  ${styleCommand("nimicoding sweep design fix-topic --run-id <id> [--slug <slug>] [--title <title>] [--admit-first-wave|--admit-wave-id <id>] [--json]")}`,
    `  ${styleCommand("nimicoding admit-high-risk-decision --from <json> --admitted-at <iso8601> [--json] [--write-spec]")}`,
    `  ${styleCommand("nimicoding closeout --skill <skill-id> --outcome <completed|blocked|failed> --verified-at <iso8601>")}`,
    `  ${styleCommand("nimicoding closeout --skill <skill-id> --outcome <completed|blocked|failed> --verified-at <iso8601> --json")}`,
    `  ${styleCommand("nimicoding closeout --skill <skill-id> --outcome <completed|blocked|failed> --verified-at <iso8601> --write-local")}`,
    `  ${styleCommand("nimicoding closeout --from <json> [--json] [--write-local]")}`,
    `  ${styleCommand("nimicoding decide-high-risk-execution --from <json> --acceptance <path> --verified-at <iso8601> [--json] [--write-local]")}`,
    `  ${styleCommand("nimicoding ingest-high-risk-execution --from <json> [--json] [--write-local]")}`,
    `  ${styleCommand("nimicoding review-high-risk-execution --from <json> [--json] [--write-local]")}`,
    `  ${styleCommand("nimicoding validate-execution-packet <path>")}`,
    `  ${styleCommand("nimicoding validate-orchestration-state <path>")}`,
    `  ${styleCommand("nimicoding validate-spec-governance --profile <profile-id> --scope <all|host-defined-scope>")}`,
    `  ${styleCommand("nimicoding validate-spec-audit [.nimi/spec/_meta/spec-generation-audit.yaml]")}`,
    `  ${styleCommand("nimicoding validate-spec-tree [.nimi/spec]")}`,
    `  ${styleCommand("nimicoding classify-spec-tree --profile <profile-id> --root .nimi/spec [--emit <path>] [--json]")}`,
    `  ${styleCommand("nimicoding generate-spec-migration-plan --profile <profile-id> --root .nimi/spec --emit .nimi/local/state/spec-surface/migration-plan.json [--json]")}`,
    `  ${styleCommand("nimicoding validate-placement --profile <profile-id> --root .nimi/spec [--json]")}`,
    `  ${styleCommand("nimicoding validate-table-family --profile <profile-id> --root .nimi/spec [--json]")}`,
    `  ${styleCommand("nimicoding validate-projection-edges --profile <profile-id> --root .nimi/spec [--json]")}`,
    `  ${styleCommand("nimicoding validate-guidance-bodies --profile <profile-id> --root .nimi/spec [--json]")}`,
    `  ${styleCommand("nimicoding validate-domain-admission --profile <profile-id> --root .nimi/spec [--json]")}`,
    `  ${styleCommand("nimicoding validate-tracked-output-admission --profile <profile-id> --root .nimi/spec [--json]")}`,
    `  ${styleCommand("nimicoding generate-spec-derived-docs --profile <profile-id> --scope <all|host-defined-scope> [--check]")}`,
    `  ${styleCommand("nimicoding validate-ai-governance --profile <profile-id> --scope <all|agents-freshness|context-budget|structure-budget|high-risk-doc-metadata>")}`,
    `  ${styleCommand("nimicoding validate-prompt <path>")}`,
    `  ${styleCommand("nimicoding validate-worker-output <path>")}`,
    `  ${styleCommand("nimicoding validate-acceptance <path>")}`,
    "",
    localize("Notes:", "说明："),
    styleMuted(localize(
      "  - `nimicoding topic` currently implements root control, Wave 2 graph/admission/freeze, Wave 3 dispatch/result/decision-review, Wave 4 remediation/overflow control, Wave 5 closure/true-close gates, Wave 6 read-only golden-fixture audit, and pending hold/resume lifecycle control",
      "  - `nimicoding topic` 当前实现 root control、Wave 2 graph/admission/freeze、Wave 3 dispatch/result/decision-review、Wave 4 remediation/overflow control、Wave 5 closure/true-close gate、Wave 6 只读 golden fixture 审计，以及 pending hold/resume 生命周期控制",
    )),
    styleMuted(localize(
      "  - `topic create` requires an explicit justification so topic entry does not silently become the default path",
      "  - `topic create` 要求显式 justification，避免 topic entry 静默变成默认路径",
    )),
    styleMuted(localize(
      "  - `nimicoding start` is the primary entrypoint; it sets up the project and prepares the next AI task",
      "  - `nimicoding start` 是主入口；它会准备项目并为下一项 AI 任务做好准备",
    )),
    styleMuted(localize(
      "  - interactive `nimicoding start` describes one option, asks once, and applies one option at a time",
      "  - 交互式 `nimicoding start` 会逐项说明、逐项确认、逐项执行",
    )),
    styleMuted(localize(
      "  - `nimicoding start` can also choose a target host and print a short paste-ready prompt directly in the terminal",
      "  - `nimicoding start` 还可以选择目标 Host，并直接在终端输出一段可粘贴的短 prompt",
    )),
    styleMuted(localize(
      "  - `nimicoding clear` removes only managed AI blocks plus package-owned .nimi/config, .nimi/contracts, and .nimi/methodology files that still match the packaged seed",
      "  - `nimicoding clear` 只会移除托管 AI 区块，以及仍与包内 seed 完全一致的 .nimi/config、.nimi/contracts、.nimi/methodology 文件",
    )),
    styleMuted(localize(
      "  - `nimicoding clear` does not remove .nimi/spec, .nimi/local, or .nimi/cache for you",
      "  - `nimicoding clear` 不会替你移除 .nimi/spec、.nimi/local 或 .nimi/cache",
    )),
    styleMuted(localize(
      "  - `nimicoding sync` is the package-owned seed projection contract: --apply rewrites drifted package_canonical files and seeds missing entries; --check exits non-zero on package_canonical drift or any missing seed; host-owned seed entries are seeded once and never overwritten",
      "  - `nimicoding sync` 是 package 拥有的 seed 投影契约：--apply 会刷新 drifted package_canonical 文件并补齐缺失 seed；--check 在 package_canonical drift 或 seed 缺失时退出非零；host-owned seed 条目仅初始化一次，之后永不覆盖",
    )),
    styleMuted(localize(
      "  - `nimicoding doctor` shows the user-facing summary; add `--verbose` for internal contract detail",
      "  - `nimicoding doctor` 默认显示用户视图；加 `--verbose` 可查看内部契约细节",
    )),
    styleMuted(localize(
      "  - `nimicoding blueprint-audit` is an optional benchmark parity check when a blueprint root is declared",
      "  - `nimicoding blueprint-audit` 是可选的 benchmark 等价检查，仅在声明 blueprint root 时使用",
    )),
    styleMuted(localize(
      "  - `nimicoding validate-spec-audit` checks whether the generated canonical files carry explicit file-level evidence, inference, and unresolved-gap tracking",
      "  - `nimicoding validate-spec-audit` 用于检查生成的 canonical 文件是否携带显式的逐文件证据、推断来源和未解决缺口记录",
    )),
    styleMuted(localize(
      "  - `nimicoding handoff --prompt` writes local prompt/json refs under .nimi/local/handoff/",
      "  - `nimicoding handoff --prompt` 会把本地 prompt/json ref 写入 .nimi/local/handoff/",
    )),
    styleMuted(localize(
      "  - use `--lang zh` or `--lang en` to switch human-readable output",
      "  - 使用 `--lang zh` 或 `--lang en` 切换人类可读输出语言",
    )),
  ];

  return `${lines.join("\n")}\n`;
}
