export const VALIDATOR_CLI_RESULT_CONTRACT = "validator-cli-result.v1";

export const VALIDATOR_NATIVE_REFUSAL_CODES = {
  EXECUTION_PACKET_MISSING: "EXECUTION_PACKET_MISSING",
  EXECUTION_PACKET_INVALID: "EXECUTION_PACKET_INVALID",
  ORCHESTRATION_STATE_MISSING: "ORCHESTRATION_STATE_MISSING",
  ORCHESTRATION_STATE_INVALID: "ORCHESTRATION_STATE_INVALID",
  PROMPT_MISSING: "PROMPT_MISSING",
  PROMPT_INVALID: "PROMPT_INVALID",
  WORKER_OUTPUT_MISSING: "WORKER_OUTPUT_MISSING",
  WORKER_OUTPUT_INVALID: "WORKER_OUTPUT_INVALID",
  RUNNER_SIGNAL_MISSING: "RUNNER_SIGNAL_MISSING",
  RUNNER_SIGNAL_INVALID: "RUNNER_SIGNAL_INVALID",
  ACCEPTANCE_MISSING: "ACCEPTANCE_MISSING",
  ACCEPTANCE_INVALID: "ACCEPTANCE_INVALID",
  SPEC_TREE_MISSING: "SPEC_TREE_MISSING",
  SPEC_TREE_INVALID: "SPEC_TREE_INVALID",
  SPEC_AUDIT_MISSING: "SPEC_AUDIT_MISSING",
  SPEC_AUDIT_INVALID: "SPEC_AUDIT_INVALID",
};

export function makeValidatorRefusal(code, message) {
  return { code, message };
}

export function normalizeArgv(args) {
  return args[0] === "--" ? args.slice(1) : args;
}
